AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Create an SNS topic and add a queue subscription

Parameters:
  Client:
    Type: String
    Description: Resource Tag
  Project:
    Type: String
    Description: A value to identify the project the resource supports
  Environment:
    Description: For example, use 'dev' or 'prd'
    Type: String
  BucketName:
    Type: String
    Description: Name of Bucket
  LambdaRoleArn:
    Type: String
    Description: ARN of lambda execution role
  GoodOlLambdaArn:
    Type: String
    Description: ARN of GoodOlLambda

  TransformLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs18.x
      Timeout: 30
      CodeUri: dist
      Handler: index.transformLambdaHandler
      Role: !GetAtt LambdaRole.Arn    

  AddLookupLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs18.x
      Timeout: 30
      CodeUri: dist
      Handler: index.addLookupLambdaHandler
      Role: !GetAtt LambdaRole.Arn         


  RoleMachineLambda:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: !Sub 'states.${AWS::Region}.amazonaws.com'
            Action: sts:AssumeRole
      Policies:
        - PolicyName: lambdaInvoke
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action: 'lambda:InvokeFunction'
                Resource:
                  - !Ref GoodOlLambdaArn
                  - !GetAtt TransformLambda.Arn
                  - !GetAtt AddLookupLambda.Arn

  StateMachineEventPasser:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      DefinitionString: !Sub |
        {
            "Comment": "AWS Step Functions Attempt",
            "StartAt": "GoodOlLambda",
            "Version": "1.0",
            "States": {
              "GoodOlLambda": {
                "Type": "Task",
                "Resource": "${GoodOlLambdaArn}",
                "Next": "TransformIt"
              },
              "TransformIt": {
                "Type": "Task",
                "Resource": "${TransformLambda.Arn}",
                "Next": "AddLookup"
              },
              "AddLookup": {
                "Type": "Task",
                "Resource": "${AddLookupLambda.Arn}",
                "Next": "Done"
              },
              "Done": {
                "Type: "Succeed"
              }
            }
        }
